-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:61fafb5fcf3da0c9f486d4962f7944fa$
-- 

return {
	texture = 'planetsPack.png',
	frames = {
			{
				name = "alya1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.691406, u1 = 0.789062, v1 = 0.789062 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alya2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.691406, u1 = 0.591797, v1 = 0.789062 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antares1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.888672, u1 = 0.394531, v1 = 0.986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antares2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.790039, u1 = 0.394531, v1 = 0.887695 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antares3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.691406, u1 = 0.394531, v1 = 0.789062 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antares4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.592773, u1 = 0.986328, v1 = 0.69043 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "artemis1-1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.592773, u1 = 0.789062, v1 = 0.69043 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "artemis1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.592773, u1 = 0.591797, v1 = 0.69043 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "castor1After.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.592773, u1 = 0.394531, v1 = 0.69043 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "castor1Before.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.888672, u1 = 0.197266, v1 = 0.986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "chara1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.790039, u1 = 0.197266, v1 = 0.887695 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "chara2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.691406, u1 = 0.197266, v1 = 0.789062 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "chara2_1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.592773, u1 = 0.197266, v1 = 0.69043 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "chara3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.494141, u1 = 0.986328, v1 = 0.591797 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cursa1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.494141, u1 = 0.789062, v1 = 0.591797 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cursa2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.494141, u1 = 0.591797, v1 = 0.591797 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "debris1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.494141, u1 = 0.394531, v1 = 0.591797 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "debris2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.494141, u1 = 0.197266, v1 = 0.591797 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "heron1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.395508, u1 = 0.986328, v1 = 0.493164 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "heron2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.395508, u1 = 0.789062, v1 = 0.493164 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "heron5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.395508, u1 = 0.591797, v1 = 0.493164 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hive.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.395508, u1 = 0.394531, v1 = 0.493164 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hydra1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.395508, u1 = 0.197266, v1 = 0.493164 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lepus.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.296875, u1 = 0.986328, v1 = 0.394531 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lilepus.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.296875, u1 = 0.789062, v1 = 0.394531 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "peach.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.296875, u1 = 0.591797, v1 = 0.394531 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.296875, u1 = 0.394531, v1 = 0.394531 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.296875, u1 = 0.197266, v1 = 0.394531 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.198242, u1 = 0.986328, v1 = 0.295898 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.198242, u1 = 0.789062, v1 = 0.295898 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.198242, u1 = 0.591797, v1 = 0.295898 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pollux6.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.198242, u1 = 0.394531, v1 = 0.295898 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "syrma1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.198242, u1 = 0.197266, v1 = 0.295898 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "syrma2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.0996094, u1 = 0.986328, v1 = 0.197266 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "syrma3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.0996094, u1 = 0.789062, v1 = 0.197266 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "syrma4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.0996094, u1 = 0.591797, v1 = 0.197266 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "syrma5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.0996094, u1 = 0.394531, v1 = 0.197266 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "theGrove.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.0996094, u1 = 0.197266, v1 = 0.197266 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vulpecula1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.791016, v0 = 0.000976562, u1 = 0.986328, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vulpecula2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.59375, v0 = 0.000976562, u1 = 0.789062, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vulpecula3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.396484, v0 = 0.000976562, u1 = 0.591797, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vulpecula4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.199219, v0 = 0.000976562, u1 = 0.394531, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vulpecula5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.197266, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

