-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:8487afc3a34ed3fc2dc69d0629c1d7a4:1/1$
-- 

return {
	texture = 'starsPack.png',
	frames = {
			{
				name = "dust1.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 500 },
				uvRect = { u0 = 0.246094, v0 = 0.753906, u1 = 0.490234, v1 = 0.998047 },
				spriteSourceSize = { width = 500, height = 500 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dust2.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 500 },
				uvRect = { u0 = 0.000976562, v0 = 0.753906, u1 = 0.245117, v1 = 0.998047 },
				spriteSourceSize = { width = 500, height = 500 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "stars1.png",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0.491211, v0 = 0.000976562, u1 = 0.741211, v1 = 0.250977 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "stars2.png",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0.000976562, v0 = 0.50293, u1 = 0.250977, v1 = 0.75293 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "stars3.png",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0.000976562, v0 = 0.251953, u1 = 0.250977, v1 = 0.501953 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "stars4.png",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.250977, v1 = 0.250977 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

