-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:faccc4a86b154955ff798c371c961a1f:1/1$
-- 

return {
	texture = 'battleFieldsPack1.png',
	frames = {
			{
				name = "generic1.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.588867, u1 = 0.500977, v1 = 0.881836 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "generic2.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.294922, u1 = 0.500977, v1 = 0.587891 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "generic3.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.501953, v0 = 0.000976562, u1 = 0.794922, v1 = 0.500977 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "generic4.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.500977, v1 = 0.293945 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

