-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:9268715243ad6545c501456ac97b91f2:1/1$
-- 

return {
	texture = 'battleFieldsPack2.png',
	frames = {
			{
				name = "generic5.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.587891, v1 = 0.500977 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

