-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:1d2cd096cb9e3b04e5dc513a3fbe8b9b:1/1$
-- 

return {
	texture = 'humanDestroyerPack.png',
	frames = {
			{
				name = "humanDestroyer1.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.487305, v0 = 0.730469, u1 = 0.804688, v1 = 0.972656 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer10.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.487305, v0 = 0.487305, u1 = 0.804688, v1 = 0.729492 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer2.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.244141, v0 = 0.487305, u1 = 0.486328, v1 = 0.804688 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "humanDestroyer3.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.5625, v0 = 0.244141, u1 = 0.879883, v1 = 0.486328 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer4.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.244141, v0 = 0.244141, u1 = 0.561523, v1 = 0.486328 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer5.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.000976562, v0 = 0.5625, u1 = 0.243164, v1 = 0.879883 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "humanDestroyer6.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.000976562, v0 = 0.244141, u1 = 0.243164, v1 = 0.561523 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "humanDestroyer7.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.637695, v0 = 0.000976562, u1 = 0.955078, v1 = 0.243164 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer8.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.319336, v0 = 0.000976562, u1 = 0.636719, v1 = 0.243164 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyer9.png",
				spriteColorRect = { x = 0, y = 0, width = 650, height = 496 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.318359, v1 = 0.243164 },
				spriteSourceSize = { width = 650, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFrontTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 150 },
				uvRect = { u0 = 0.0620117, v0 = 0.880859, u1 = 0.12207, v1 = 0.954102 },
				spriteSourceSize = { width = 123, height = 150 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerGunTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 150 },
				uvRect = { u0 = 0.000976562, v0 = 0.880859, u1 = 0.0610352, v1 = 0.954102 },
				spriteSourceSize = { width = 123, height = 150 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.244141, v0 = 0.805664, u1 = 0.390625, v1 = 0.952148 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRearTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 150 },
				uvRect = { u0 = 0.0620117, v0 = 0.880859, u1 = 0.12207, v1 = 0.954102 },
				spriteSourceSize = { width = 123, height = 150 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

