-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:e19094a7a1aa822d43d84a8ef4d4d59c:1/1$
-- 

return {
	texture = 'shipsPack.png',
	frames = {
			{
				name = "pcShip.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 512 },
				uvRect = { u0 = 0.000976562, v0 = 0.251953, u1 = 0.125977, v1 = 0.501953 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle1.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.757324, v0 = 0.000976562, u1 = 0.994141, v1 = 0.0981445 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pcShipForBattle10.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.519531, v0 = 0.000976562, u1 = 0.756348, v1 = 0.0981445 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pcShipForBattle11.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.421387, v0 = 0.23877, u1 = 0.518555, v1 = 0.475586 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle12.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.421387, v0 = 0.000976562, u1 = 0.518555, v1 = 0.237793 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle13.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.393555, v0 = 0.714355, u1 = 0.490723, v1 = 0.951172 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle14.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.393555, v0 = 0.476562, u1 = 0.490723, v1 = 0.713379 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle15.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.323242, v0 = 0.23877, u1 = 0.42041, v1 = 0.475586 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle16.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.323242, v0 = 0.000976562, u1 = 0.42041, v1 = 0.237793 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle17.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.29541, v0 = 0.714355, u1 = 0.392578, v1 = 0.951172 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle18.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.29541, v0 = 0.476562, u1 = 0.392578, v1 = 0.713379 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle19.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.225098, v0 = 0.23877, u1 = 0.322266, v1 = 0.475586 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle2.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.225098, v0 = 0.000976562, u1 = 0.322266, v1 = 0.237793 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle20.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.197266, v0 = 0.714355, u1 = 0.294434, v1 = 0.951172 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle3.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.197266, v0 = 0.476562, u1 = 0.294434, v1 = 0.713379 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle4.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.126953, v0 = 0.23877, u1 = 0.224121, v1 = 0.475586 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle5.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.126953, v0 = 0.000976562, u1 = 0.224121, v1 = 0.237793 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle6.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.0991211, v0 = 0.740723, u1 = 0.196289, v1 = 0.977539 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle7.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.0991211, v0 = 0.50293, u1 = 0.196289, v1 = 0.739746 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle8.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.000976562, v0 = 0.740723, u1 = 0.0981445, v1 = 0.977539 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipForBattle9.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 485 },
				uvRect = { u0 = 0.000976562, v0 = 0.50293, u1 = 0.0981445, v1 = 0.739746 },
				spriteSourceSize = { width = 199, height = 485 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pcShipNoOutline.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 512 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.125977, v1 = 0.250977 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

