-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:6abfc422652783686036e1a7041469c7$
-- 

return {
	texture = 'takatakaPack.png',
	frames = {
			{
				name = "takatakaFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.479492, v0 = 0.794434, u1 = 0.636719, v1 = 0.989746 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.320312, v0 = 0.786133, u1 = 0.477539, v1 = 0.981445 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.161133, v0 = 0.786133, u1 = 0.318359, v1 = 0.981445 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.00195312, v0 = 0.786133, u1 = 0.15918, v1 = 0.981445 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.787109, v0 = 0.589844, u1 = 0.944336, v1 = 0.785156 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.394531, v0 = 0.567383, u1 = 0.785156, v1 = 0.645996 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.00195312, v0 = 0.567383, u1 = 0.392578, v1 = 0.645996 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.800781, v0 = 0.393555, u1 = 0.958008, v1 = 0.588867 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.800781, v0 = 0.197266, u1 = 0.958008, v1 = 0.392578 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 161 },
				uvRect = { u0 = 0.800781, v0 = 0.000976562, u1 = 0.958008, v1 = 0.196289 },
				spriteSourceSize = { width = 400, height = 161 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighterIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.638672, v0 = 0.794434, u1 = 0.931641, v1 = 0.940918 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.401367, v0 = 0.454102, u1 = 0.798828, v1 = 0.566406 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.454102, u1 = 0.399414, v1 = 0.566406 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.401367, v0 = 0.34082, u1 = 0.798828, v1 = 0.453125 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.34082, u1 = 0.399414, v1 = 0.453125 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.401367, v0 = 0.227539, u1 = 0.798828, v1 = 0.339844 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.227539, u1 = 0.399414, v1 = 0.339844 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.401367, v0 = 0.114258, u1 = 0.798828, v1 = 0.226562 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.114258, u1 = 0.399414, v1 = 0.226562 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.401367, v0 = 0.000976562, u1 = 0.798828, v1 = 0.113281 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 407, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.399414, v1 = 0.113281 },
				spriteSourceSize = { width = 407, height = 230 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaLargeFighterIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.479492, v0 = 0.646973, u1 = 0.772461, v1 = 0.793457 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

