-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d8bc01ba0d8adecf5d3002c6f2d2071c$
-- 

return {
	texture = 'starMapPack.png',
	frames = {
			{
				name = "blueStar.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.160156, v0 = 0.735352, u1 = 0.257812, v1 = 0.78418 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grid.png",
				spriteColorRect = { x = 0, y = 0, width = 160, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.735352, u1 = 0.158203, v1 = 0.833008 },
				spriteSourceSize = { width = 160, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "orangeStar.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.101562, v0 = 0.833984, u1 = 0.199219, v1 = 0.882812 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "redStar.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.00195312, v0 = 0.933594, u1 = 0.0996094, v1 = 0.982422 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "starmapBackground.png",
				spriteColorRect = { x = 0, y = 0, width = 1502, height = 1002 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.980469, v1 = 0.734375 },
				spriteSourceSize = { width = 1502, height = 1002 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "whiteStar.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.00195312, v0 = 0.883789, u1 = 0.0996094, v1 = 0.932617 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "yellowStar.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.00195312, v0 = 0.833984, u1 = 0.0996094, v1 = 0.882812 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

