-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:7bc060890d08a02ae01e98a3c2d4b651:fe8f19a2874e5db36b5882419ef42176:5dfce2df7be76d8977322384255eceea$
-- 

return {
	texture = 'crewPack.png',
	frames = {
			{
				name = "charlie.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.591797, v0 = 0.591797, u1 = 0.884766, v1 = 0.884766 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "clarenceWithGoat.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.591797, v0 = 0.296875, u1 = 0.884766, v1 = 0.589844 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "clarenceWithoutGoat.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.634766, v0 = 0.00195312, u1 = 0.927734, v1 = 0.294922 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "frank.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.296875, v0 = 0.634766, u1 = 0.589844, v1 = 0.927734 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "frankNude.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.339844, v0 = 0.00195312, u1 = 0.632812, v1 = 0.294922 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jarvis.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.296875, v0 = 0.339844, u1 = 0.589844, v1 = 0.632812 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "oleg.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.00195312, v0 = 0.634766, u1 = 0.294922, v1 = 0.927734 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selectedProp.png",
				spriteColorRect = { x = 0, y = 0, width = 344, height = 344 },
				uvRect = { u0 = 0.00195312, v0 = 0.00195312, u1 = 0.337891, v1 = 0.337891 },
				spriteSourceSize = { width = 344, height = 344 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "yepp.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.00195312, v0 = 0.339844, u1 = 0.294922, v1 = 0.632812 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

