-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:f958c02a988f18acd0c2141da491aa56:1/1$
-- 

return {
	texture = 'pirateDestroyerPack.png',
	frames = {
			{
				name = "pirateDestroyer1.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.393555, v0 = 0.393555, u1 = 0.588867, v1 = 0.710449 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer10.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.197266, v0 = 0.711426, u1 = 0.51416, v1 = 0.906738 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateDestroyer2.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.197266, v0 = 0.393555, u1 = 0.392578, v1 = 0.710449 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer3.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.515137, v0 = 0.197266, u1 = 0.832031, v1 = 0.392578 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateDestroyer4.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.197266, v0 = 0.197266, u1 = 0.51416, v1 = 0.392578 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateDestroyer5.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.515137, v0 = 0.000976562, u1 = 0.832031, v1 = 0.196289 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateDestroyer6.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.197266, v0 = 0.000976562, u1 = 0.51416, v1 = 0.196289 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateDestroyer7.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.000976562, v0 = 0.636719, u1 = 0.196289, v1 = 0.953613 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer8.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.000976562, v0 = 0.318848, u1 = 0.196289, v1 = 0.635742 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer9.png",
				spriteColorRect = { x = 0, y = 0, width = 400, height = 649 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.196289, v1 = 0.317871 },
				spriteSourceSize = { width = 400, height = 649 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyerIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.833008, v0 = 0.000976562, u1 = 0.979492, v1 = 0.147461 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyerTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 137, height = 150 },
				uvRect = { u0 = 0.833008, v0 = 0.148438, u1 = 0.90625, v1 = 0.215332 },
				spriteSourceSize = { width = 137, height = 150 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

