-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:46d623f9f807a4d5ddf68503d5a0148a$
-- 

return {
	texture = 'piratePack.png',
	frames = {
			{
				name = "pirateFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.8125, v0 = 0.483887, u1 = 0.950195, v1 = 0.630371 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.37793, v0 = 0.886719, u1 = 0.670898, v1 = 0.955566 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.672852, v0 = 0.809082, u1 = 0.810547, v1 = 0.955566 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.807617, v0 = 0.336426, u1 = 0.945312, v1 = 0.48291 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.672852, v0 = 0.483887, u1 = 0.810547, v1 = 0.630371 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.517578, v0 = 0.739258, u1 = 0.810547, v1 = 0.808105 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.517578, v0 = 0.669434, u1 = 0.810547, v1 = 0.738281 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.37793, v0 = 0.816895, u1 = 0.670898, v1 = 0.885742 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.37793, v0 = 0.669434, u1 = 0.515625, v1 = 0.815918 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 141, height = 300 },
				uvRect = { u0 = 0.667969, v0 = 0.336426, u1 = 0.805664, v1 = 0.48291 },
				spriteSourceSize = { width = 141, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateFighterIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.37793, v0 = 0.521973, u1 = 0.670898, v1 = 0.668457 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.582031, v0 = 0.000976562, u1 = 0.870117, v1 = 0.187988 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.291992, v0 = 0.376953, u1 = 0.666016, v1 = 0.520996 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateMissleFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.291992, v0 = 0.188965, u1 = 0.580078, v1 = 0.375977 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.291992, v0 = 0.000976562, u1 = 0.580078, v1 = 0.187988 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.85498, u1 = 0.375977, v1 = 0.999023 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateMissleFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.709961, u1 = 0.375977, v1 = 0.854004 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateMissleFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.564941, u1 = 0.375977, v1 = 0.708984 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pirateMissleFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.376953, u1 = 0.290039, v1 = 0.563965 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.188965, u1 = 0.290039, v1 = 0.375977 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 295, height = 383 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.290039, v1 = 0.187988 },
				spriteSourceSize = { width = 295, height = 383 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateMissleFighterIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.582031, v0 = 0.188965, u1 = 0.875, v1 = 0.335449 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

