-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:ddb96061f90688e6f547d624e87914d0:7b1028a9d800dc10c69eff5eeae234e2:4cbe50e7c02c0c8b706476a3932d4119$
-- 

return {
	texture = 'sharedPack.png',
	frames = {
			{
				name = "arrowLeft.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 235 },
				uvRect = { u0 = 0.879395, v0 = 0.365234, u1 = 0.994141, v1 = 0.511719 },
				spriteSourceSize = { width = 300, height = 235 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "arrowLeftPressed.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 235 },
				uvRect = { u0 = 0.740723, v0 = 0.873535, u1 = 0.887207, v1 = 0.988281 },
				spriteSourceSize = { width = 300, height = 235 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrowRight.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 235 },
				uvRect = { u0 = 0.735352, v0 = 0.610352, u1 = 0.881836, v1 = 0.725098 },
				spriteSourceSize = { width = 300, height = 235 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrowRightPressed.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 235 },
				uvRect = { u0 = 0.625, v0 = 0.79541, u1 = 0.739746, v1 = 0.941895 },
				spriteSourceSize = { width = 300, height = 235 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "asteroid1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.882812, v0 = 0.512695, u1 = 0.980469, v1 = 0.610352 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "asteroid2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.891113, v0 = 0.209961, u1 = 0.98877, v1 = 0.307617 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "asteroid3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.891113, v0 = 0.111328, u1 = 0.98877, v1 = 0.208984 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "asteroid4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.895508, v0 = 0.0126953, u1 = 0.993164, v1 = 0.110352 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "asteroid5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.386719, v0 = 0.294922, u1 = 0.484375, v1 = 0.392578 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bannerBackground.png",
				spriteColorRect = { x = 0, y = 0, width = 1100, height = 100 },
				uvRect = { u0 = 0.000976562, v0 = 0.294922, u1 = 0.0498047, v1 = 0.832031 },
				spriteSourceSize = { width = 1100, height = 100 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "buttonSelected.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 201 },
				uvRect = { u0 = 0.501953, v0 = 0.26416, u1 = 0.746094, v1 = 0.362305 },
				spriteSourceSize = { width = 500, height = 201 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "checkBoxChecked.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.882812, v0 = 0.611328, u1 = 0.907227, v1 = 0.635742 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "checkBoxUnchecked.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.940918, v0 = 0.308594, u1 = 0.965332, v1 = 0.333008 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "circuitButton.png",
				spriteColorRect = { x = 0, y = 0, width = 602, height = 218 },
				uvRect = { u0 = 0.501953, v0 = 0.0126953, u1 = 0.795898, v1 = 0.119141 },
				spriteSourceSize = { width = 602, height = 218 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "circuitButtonPressed.png",
				spriteColorRect = { x = 0, y = 0, width = 602, height = 218 },
				uvRect = { u0 = 0.0917969, v0 = 0.294922, u1 = 0.385742, v1 = 0.401367 },
				spriteSourceSize = { width = 602, height = 218 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "closest.png",
				spriteColorRect = { x = 0, y = 0, width = 235, height = 300 },
				uvRect = { u0 = 0.361816, v0 = 0.794922, u1 = 0.476562, v1 = 0.941406 },
				spriteSourceSize = { width = 235, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "closestPressed.png",
				spriteColorRect = { x = 0, y = 0, width = 235, height = 300 },
				uvRect = { u0 = 0.246094, v0 = 0.837891, u1 = 0.36084, v1 = 0.984375 },
				spriteSourceSize = { width = 235, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cross.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.361816, v0 = 0.942383, u1 = 0.38623, v1 = 0.966797 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat1.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.735352, v0 = 0.365234, u1 = 0.878418, v1 = 0.609375 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "defeat10.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.480957, v0 = 0.651367, u1 = 0.725098, v1 = 0.794434 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat2.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.490234, v0 = 0.507324, u1 = 0.734375, v1 = 0.650391 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat3.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.490234, v0 = 0.363281, u1 = 0.734375, v1 = 0.506348 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat4.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.336914, v0 = 0.549805, u1 = 0.47998, v1 = 0.793945 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "defeat5.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.74707, v0 = 0.120117, u1 = 0.890137, v1 = 0.364258 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "defeat6.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.000976562, v0 = 0.837891, u1 = 0.245117, v1 = 0.980957 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat7.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.0917969, v0 = 0.693848, u1 = 0.335938, v1 = 0.836914 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat8.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.0917969, v0 = 0.549805, u1 = 0.335938, v1 = 0.692871 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "defeat9.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 293 },
				uvRect = { u0 = 0.501953, v0 = 0.120117, u1 = 0.746094, v1 = 0.263184 },
				spriteSourceSize = { width = 500, height = 293 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dialogOptionEven.png",
				spriteColorRect = { x = 0, y = 0, width = 1100, height = 40 },
				uvRect = { u0 = 0.0712891, v0 = 0.294922, u1 = 0.0908203, v1 = 0.832031 },
				spriteSourceSize = { width = 1100, height = 40 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "dialogOptionOdd.png",
				spriteColorRect = { x = 0, y = 0, width = 1100, height = 40 },
				uvRect = { u0 = 0.0507812, v0 = 0.294922, u1 = 0.0703125, v1 = 0.832031 },
				spriteSourceSize = { width = 1100, height = 40 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "directionIndicator.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 1000 },
				uvRect = { u0 = 0.501953, v0 = 0.000976562, u1 = 0.990234, v1 = 0.0117188 },
				spriteSourceSize = { width = 22, height = 1000 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "reticle.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.796875, v0 = 0.0126953, u1 = 0.894531, v1 = 0.110352 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selectArrow.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 110 },
				uvRect = { u0 = 0.891113, v0 = 0.308594, u1 = 0.939941, v1 = 0.362305 },
				spriteSourceSize = { width = 100, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "starBackground.png",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 300 },
				uvRect = { u0 = 0.0917969, v0 = 0.402344, u1 = 0.341797, v1 = 0.548828 },
				spriteSourceSize = { width = 512, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "startScreenBackground.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.500977, v1 = 0.293945 },
				spriteSourceSize = { width = 1024, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wheel.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.740723, v0 = 0.726074, u1 = 0.887207, v1 = 0.872559 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wheelPointer.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 300 },
				uvRect = { u0 = 0.000976562, v0 = 0.981934, u1 = 0.147461, v1 = 0.984863 },
				spriteSourceSize = { width = 6, height = 300 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "zoom.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.477539, v0 = 0.79541, u1 = 0.624023, v1 = 0.941895 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zoomPressed.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.342773, v0 = 0.402344, u1 = 0.489258, v1 = 0.548828 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

