-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:16d95db955c6754d0a8f717a4389281c:1/1$
-- 

return {
	texture = 'weaponsPack.png',
	frames = {
			{
				name = "antVenom1.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.449219, v0 = 0.152832, u1 = 0.49707, v1 = 0.205078 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom10.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.449219, v0 = 0.0996094, u1 = 0.49707, v1 = 0.151855 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom2.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.400391, v0 = 0.152832, u1 = 0.448242, v1 = 0.205078 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom3.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.400391, v0 = 0.0996094, u1 = 0.448242, v1 = 0.151855 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom4.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.245117, v0 = 0.925781, u1 = 0.292969, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom5.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.196289, v0 = 0.925781, u1 = 0.244141, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom6.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.147461, v0 = 0.925781, u1 = 0.195312, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom7.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.0986328, v0 = 0.925781, u1 = 0.146484, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom8.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.0498047, v0 = 0.925781, u1 = 0.0976562, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antVenom9.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 107 },
				uvRect = { u0 = 0.000976562, v0 = 0.925781, u1 = 0.0488281, v1 = 0.978027 },
				spriteSourceSize = { width = 98, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo1.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.611328, v0 = 0.0263672, u1 = 0.635742, v1 = 0.0473633 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antimatterTorpedo10.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.611328, v0 = 0.000976562, u1 = 0.632324, v1 = 0.0253906 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo2.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.603516, v0 = 0.0761719, u1 = 0.62793, v1 = 0.097168 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antimatterTorpedo3.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.603516, v0 = 0.0507812, u1 = 0.624512, v1 = 0.0751953 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo4.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.609863, v0 = 0.149414, u1 = 0.630859, v1 = 0.173828 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo5.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.588867, v0 = 0.124023, u1 = 0.609863, v1 = 0.148438 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo6.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.588867, v0 = 0.0986328, u1 = 0.609863, v1 = 0.123047 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo7.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.590332, v0 = 0.17627, u1 = 0.614746, v1 = 0.197266 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antimatterTorpedo8.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.580078, v0 = 0.199219, u1 = 0.601074, v1 = 0.223633 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antimatterTorpedo9.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				uvRect = { u0 = 0.587891, v0 = 0.150879, u1 = 0.608887, v1 = 0.175293 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cannon.png",
				spriteColorRect = { x = 0, y = 0, width = 71, height = 100 },
				uvRect = { u0 = 0.25293, v0 = 0.865723, u1 = 0.287598, v1 = 0.914551 },
				spriteSourceSize = { width = 71, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_0.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.25293, v0 = 0.42041, u1 = 0.37793, v1 = 0.54541 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_1.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.274414, v0 = 0.126953, u1 = 0.399414, v1 = 0.251953 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_10.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.274414, v0 = 0.000976562, u1 = 0.399414, v1 = 0.125977 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_11.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.25293, v0 = 0.294434, u1 = 0.37793, v1 = 0.419434 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_12.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.126953, v0 = 0.799805, u1 = 0.251953, v1 = 0.924805 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_13.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.126953, v0 = 0.673828, u1 = 0.251953, v1 = 0.798828 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_14.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.126953, v0 = 0.547852, u1 = 0.251953, v1 = 0.672852 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_15.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.126953, v0 = 0.421875, u1 = 0.251953, v1 = 0.546875 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_16.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.25293, v0 = 0.42041, u1 = 0.37793, v1 = 0.54541 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_17.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.274414, v0 = 0.126953, u1 = 0.399414, v1 = 0.251953 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_18.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.148438, v0 = 0.126953, u1 = 0.273438, v1 = 0.251953 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_19.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.148438, v0 = 0.000976562, u1 = 0.273438, v1 = 0.125977 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_2.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.148438, v0 = 0.126953, u1 = 0.273438, v1 = 0.251953 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_3.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.148438, v0 = 0.000976562, u1 = 0.273438, v1 = 0.125977 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_4.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.126953, v0 = 0.295898, u1 = 0.251953, v1 = 0.420898 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_5.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.000976562, v0 = 0.799805, u1 = 0.125977, v1 = 0.924805 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_6.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.000976562, v0 = 0.673828, u1 = 0.125977, v1 = 0.798828 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_7.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.000976562, v0 = 0.547852, u1 = 0.125977, v1 = 0.672852 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_8.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.000976562, v0 = 0.421875, u1 = 0.125977, v1 = 0.546875 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "explode_9.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.000976562, v0 = 0.295898, u1 = 0.125977, v1 = 0.420898 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.498535, v0 = 0.972168, u1 = 0.518555, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo10.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.477539, v0 = 0.972168, u1 = 0.497559, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo2.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.456543, v0 = 0.972168, u1 = 0.476562, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo3.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.435547, v0 = 0.972168, u1 = 0.455566, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo4.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.414551, v0 = 0.972168, u1 = 0.43457, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo5.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.393555, v0 = 0.972168, u1 = 0.413574, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo6.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.372559, v0 = 0.972168, u1 = 0.392578, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo7.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.351562, v0 = 0.972168, u1 = 0.371582, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo8.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.330566, v0 = 0.972168, u1 = 0.350586, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fissionTorpedo9.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.30957, v0 = 0.972168, u1 = 0.32959, v1 = 0.998047 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.5, v0 = 0.487305, u1 = 0.514648, v1 = 0.501953 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.484375, v0 = 0.487305, u1 = 0.499023, v1 = 0.501953 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit3.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.472656, v0 = 0.529785, u1 = 0.487305, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit4.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.457031, v0 = 0.529785, u1 = 0.47168, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit5.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.441406, v0 = 0.529785, u1 = 0.456055, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit6.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.425781, v0 = 0.529785, u1 = 0.44043, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit7.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.410156, v0 = 0.529785, u1 = 0.424805, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit8.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.394531, v0 = 0.529785, u1 = 0.40918, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit9.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.378906, v0 = 0.529785, u1 = 0.393555, v1 = 0.544434 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront1.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.378906, v0 = 0.397949, u1 = 0.483398, v1 = 0.503418 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront10.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.378906, v0 = 0.291504, u1 = 0.483398, v1 = 0.396973 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront2.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.399414, v0 = 0.865723, u1 = 0.503906, v1 = 0.971191 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront3.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.759277, u1 = 0.462891, v1 = 0.864746 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront4.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.652832, u1 = 0.462891, v1 = 0.758301 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront5.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.546387, u1 = 0.462891, v1 = 0.651855 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront6.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.293945, v0 = 0.865723, u1 = 0.398438, v1 = 0.971191 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront7.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.759277, u1 = 0.357422, v1 = 0.864746 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront8.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.652832, u1 = 0.357422, v1 = 0.758301 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerFront9.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.546387, u1 = 0.357422, v1 = 0.651855 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear1.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.378906, v0 = 0.397949, u1 = 0.483398, v1 = 0.503418 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear10.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.378906, v0 = 0.291504, u1 = 0.483398, v1 = 0.396973 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear2.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.399414, v0 = 0.865723, u1 = 0.503906, v1 = 0.971191 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear3.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.759277, u1 = 0.462891, v1 = 0.864746 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear4.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.652832, u1 = 0.462891, v1 = 0.758301 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear5.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.358398, v0 = 0.546387, u1 = 0.462891, v1 = 0.651855 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear6.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.293945, v0 = 0.865723, u1 = 0.398438, v1 = 0.971191 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear7.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.759277, u1 = 0.357422, v1 = 0.864746 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear8.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.652832, u1 = 0.357422, v1 = 0.758301 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "humanDestroyerRear9.png",
				spriteColorRect = { x = 0, y = 0, width = 214, height = 216 },
				uvRect = { u0 = 0.25293, v0 = 0.546387, u1 = 0.357422, v1 = 0.651855 },
				spriteSourceSize = { width = 214, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam1.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.319824, v0 = 0.25293, u1 = 0.337891, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam10.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.300781, v0 = 0.25293, u1 = 0.318848, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.281738, v0 = 0.25293, u1 = 0.299805, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.262695, v0 = 0.25293, u1 = 0.280762, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam4.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.243652, v0 = 0.25293, u1 = 0.261719, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam5.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.224609, v0 = 0.25293, u1 = 0.242676, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam6.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.205566, v0 = 0.25293, u1 = 0.223633, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam7.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.186523, v0 = 0.25293, u1 = 0.20459, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam8.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.16748, v0 = 0.25293, u1 = 0.185547, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ionBeam9.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 83 },
				uvRect = { u0 = 0.148438, v0 = 0.25293, u1 = 0.166504, v1 = 0.293457 },
				spriteSourceSize = { width = 37, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "laserBeam1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.359863, v0 = 0.25293, u1 = 0.379883, v1 = 0.290527 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "laserBeam10.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.338867, v0 = 0.25293, u1 = 0.358887, v1 = 0.290527 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "laserBeam2.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.270996, v0 = 0.979004, u1 = 0.308594, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam3.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.232422, v0 = 0.979004, u1 = 0.27002, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam4.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.193848, v0 = 0.979004, u1 = 0.231445, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam5.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.155273, v0 = 0.979004, u1 = 0.192871, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam6.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.116699, v0 = 0.979004, u1 = 0.154297, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam7.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.078125, v0 = 0.979004, u1 = 0.115723, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam8.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.0395508, v0 = 0.979004, u1 = 0.0771484, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "laserBeam9.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 77 },
				uvRect = { u0 = 0.000976562, v0 = 0.979004, u1 = 0.0385742, v1 = 0.999023 },
				spriteSourceSize = { width = 41, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer1.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.55127, v0 = 0.0532227, u1 = 0.602539, v1 = 0.0976562 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer10.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.543457, v0 = 0.0986328, u1 = 0.587891, v1 = 0.149902 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer2.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.544434, v0 = 0.000976562, u1 = 0.588867, v1 = 0.0522461 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer3.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.499023, v0 = 0.0532227, u1 = 0.550293, v1 = 0.0976562 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer4.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.499023, v0 = 0.000976562, u1 = 0.543457, v1 = 0.0522461 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer5.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.504883, v0 = 0.204102, u1 = 0.556152, v1 = 0.248535 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer6.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.498047, v0 = 0.151855, u1 = 0.54248, v1 = 0.203125 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer7.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.498047, v0 = 0.0996094, u1 = 0.54248, v1 = 0.150879 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer8.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.452637, v0 = 0.206055, u1 = 0.503906, v1 = 0.250488 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer9.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 105 },
				uvRect = { u0 = 0.400391, v0 = 0.206055, u1 = 0.45166, v1 = 0.250488 },
				spriteSourceSize = { width = 91, height = 105 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.311523, u1 = 0.537598, v1 = 0.335938 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.629395, v0 = 0.117676, u1 = 0.639648, v1 = 0.14209 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.629395, v0 = 0.0922852, u1 = 0.639648, v1 = 0.116699 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.533203, v0 = 0.274902, u1 = 0.557617, v1 = 0.285156 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.507812, v0 = 0.274902, u1 = 0.532227, v1 = 0.285156 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.482422, v0 = 0.276855, u1 = 0.506836, v1 = 0.287109 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.457031, v0 = 0.276855, u1 = 0.481445, v1 = 0.287109 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.431641, v0 = 0.276855, u1 = 0.456055, v1 = 0.287109 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.40625, v0 = 0.276855, u1 = 0.430664, v1 = 0.287109 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 50 },
				uvRect = { u0 = 0.380859, v0 = 0.27832, u1 = 0.405273, v1 = 0.288574 },
				spriteSourceSize = { width = 21, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "nuclearTorpedo1.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.67041, v0 = 0.000976562, u1 = 0.687988, v1 = 0.0253906 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo10.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.662109, v0 = 0.0263672, u1 = 0.686523, v1 = 0.0439453 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "nuclearTorpedo2.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.644043, v0 = 0.0449219, u1 = 0.661621, v1 = 0.0693359 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo3.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.628906, v0 = 0.0737305, u1 = 0.65332, v1 = 0.0913086 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "nuclearTorpedo4.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.61084, v0 = 0.123535, u1 = 0.628418, v1 = 0.147949 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo5.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.61084, v0 = 0.0981445, u1 = 0.628418, v1 = 0.122559 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo6.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.651855, v0 = 0.000976562, u1 = 0.669434, v1 = 0.0253906 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo7.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.636719, v0 = 0.0263672, u1 = 0.661133, v1 = 0.0439453 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "nuclearTorpedo8.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.625488, v0 = 0.0483398, u1 = 0.643066, v1 = 0.0727539 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "nuclearTorpedo9.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 50 },
				uvRect = { u0 = 0.633301, v0 = 0.000976562, u1 = 0.650879, v1 = 0.0253906 },
				spriteSourceSize = { width = 36, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer1.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.505859, v0 = 0.387695, u1 = 0.526367, v1 = 0.436523 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer10.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.505859, v0 = 0.337891, u1 = 0.526367, v1 = 0.386719 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer2.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.505859, v0 = 0.288086, u1 = 0.526367, v1 = 0.336914 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer3.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.484375, v0 = 0.4375, u1 = 0.504883, v1 = 0.486328 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer4.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.484375, v0 = 0.387695, u1 = 0.504883, v1 = 0.436523 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer5.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.484375, v0 = 0.337891, u1 = 0.504883, v1 = 0.386719 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer6.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.484375, v0 = 0.288086, u1 = 0.504883, v1 = 0.336914 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer7.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.463867, v0 = 0.54541, u1 = 0.484375, v1 = 0.594238 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer8.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.543457, v0 = 0.150879, u1 = 0.563965, v1 = 0.199707 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pirateDestroyer9.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 100 },
				uvRect = { u0 = 0.589844, v0 = 0.000976562, u1 = 0.610352, v1 = 0.0498047 },
				spriteSourceSize = { width = 42, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon1.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.564941, v0 = 0.17627, u1 = 0.589355, v1 = 0.198242 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "plasmaCannon10.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.564941, v0 = 0.150879, u1 = 0.586914, v1 = 0.175293 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon2.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.557129, v0 = 0.226074, u1 = 0.581543, v1 = 0.248047 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "plasmaCannon3.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.557129, v0 = 0.200684, u1 = 0.579102, v1 = 0.225098 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon4.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.553223, v0 = 0.249512, u1 = 0.575195, v1 = 0.273926 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon5.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.286133, u1 = 0.549316, v1 = 0.310547 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon6.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.505859, v0 = 0.462891, u1 = 0.530273, v1 = 0.484863 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "plasmaCannon7.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.505859, v0 = 0.4375, u1 = 0.527832, v1 = 0.461914 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon8.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.530273, v0 = 0.249512, u1 = 0.552246, v1 = 0.273926 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "plasmaCannon9.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 50 },
				uvRect = { u0 = 0.478516, v0 = 0.504395, u1 = 0.500488, v1 = 0.528809 },
				spriteSourceSize = { width = 45, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shieldHit.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.400391, v0 = 0.000976562, u1 = 0.498047, v1 = 0.0986328 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shockwave1.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.000976562, v0 = 0.148438, u1 = 0.147461, v1 = 0.294922 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shockwave2.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.147461, v1 = 0.147461 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.537109, v0 = 0.362305, u1 = 0.545898, v1 = 0.386719 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.538574, v0 = 0.311523, u1 = 0.547363, v1 = 0.335938 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.537109, v0 = 0.336914, u1 = 0.545898, v1 = 0.361328 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.528809, v0 = 0.432617, u1 = 0.537598, v1 = 0.457031 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.422852, u1 = 0.551758, v1 = 0.431641 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.413086, u1 = 0.551758, v1 = 0.421875 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.387695, u1 = 0.536133, v1 = 0.412109 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.362305, u1 = 0.536133, v1 = 0.386719 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.527344, v0 = 0.336914, u1 = 0.536133, v1 = 0.361328 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "takatakaFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 50 },
				uvRect = { u0 = 0.25293, v0 = 0.915527, u1 = 0.277344, v1 = 0.924316 },
				spriteSourceSize = { width = 18, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.505371, v0 = 0.249512, u1 = 0.529297, v1 = 0.273926 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.480469, v0 = 0.251465, u1 = 0.504395, v1 = 0.275879 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.455566, v0 = 0.251465, u1 = 0.479492, v1 = 0.275879 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.430664, v0 = 0.251465, u1 = 0.45459, v1 = 0.275879 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.405762, v0 = 0.251465, u1 = 0.429688, v1 = 0.275879 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.453613, v0 = 0.504395, u1 = 0.477539, v1 = 0.528809 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.428711, v0 = 0.504395, u1 = 0.452637, v1 = 0.528809 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.403809, v0 = 0.504395, u1 = 0.427734, v1 = 0.528809 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.378906, v0 = 0.504395, u1 = 0.402832, v1 = 0.528809 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "takatakaLargeFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 49 },
				uvRect = { u0 = 0.380859, v0 = 0.25293, u1 = 0.404785, v1 = 0.277344 },
				spriteSourceSize = { width = 50, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

