-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:109e4d0caf1262c7abae4742f50e26bd:1/1$
-- 

return {
	texture = 'tutorialPack.png',
	frames = {
			{
				name = "battle.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.686523, v0 = 0.540039, u1 = 0.881836, v1 = 0.881836 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "closest.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.34375, v0 = 0.686523, u1 = 0.685547, v1 = 0.881836 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "goToMenu.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.589844, v0 = 0.34375, u1 = 0.931641, v1 = 0.539062 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "goToStar.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.393555, v0 = 0.197266, u1 = 0.588867, v1 = 0.539062 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "loadout.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.197266, v0 = 0.34375, u1 = 0.392578, v1 = 0.685547 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "move.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.000976562, v0 = 0.686523, u1 = 0.342773, v1 = 0.881836 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "navigation.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.000976562, v0 = 0.34375, u1 = 0.196289, v1 = 0.685547 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "pinchTutorial.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.686523, v0 = 0.000976562, u1 = 0.881836, v1 = 0.342773 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "select.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.34375, v0 = 0.000976562, u1 = 0.685547, v1 = 0.196289 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zoom.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.342773, v1 = 0.196289 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

