-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:fe4a738d7a9306338668c59848d1b779:1/1$
-- 

return {
	texture = 'introPack.png',
	frames = {
			{
				name = "introScene1.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.394531, v0 = 0.589844, u1 = 0.785156, v1 = 0.931641 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "introScene2.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.589844, u1 = 0.392578, v1 = 0.931641 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "introScene3.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.393555, u1 = 0.685547, v1 = 0.588867 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "introScene4.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.197266, u1 = 0.685547, v1 = 0.392578 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "introScene5.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.685547, v1 = 0.196289 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

