-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:57c153d27fdbbf5c9a0b858533a92ccb$
-- 

return {
	texture = 'locationsPack.png',
	frames = {
			{
				name = "blueStar.png",
				spriteColorRect = { x = 0, y = 0, width = 600, height = 600 },
				uvRect = { u0 = 0.00195312, v0 = 0.588867, u1 = 0.587891, v1 = 0.881836 },
				spriteSourceSize = { width = 600, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "redStar.png",
				spriteColorRect = { x = 0, y = 0, width = 600, height = 600 },
				uvRect = { u0 = 0.00195312, v0 = 0.294922, u1 = 0.587891, v1 = 0.587891 },
				spriteSourceSize = { width = 600, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "yellowStar.png",
				spriteColorRect = { x = 0, y = 0, width = 600, height = 600 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.587891, v1 = 0.293945 },
				spriteSourceSize = { width = 600, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

