-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:c3787dfaba69a9c6b783eabba0225af4:1/1$
-- 

return {
	texture = 'splashPack.png',
	frames = {
			{
				name = "moaiattribution.png",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 450 },
				uvRect = { u0 = 0.00195312, v0 = 0.272949, u1 = 0.441406, v1 = 0.772949 },
				spriteSourceSize = { width = 1024, height = 450 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "poorWillLogo.png",
				spriteColorRect = { x = 0, y = 0, width = 1002, height = 555 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.980469, v1 = 0.271973 },
				spriteSourceSize = { width = 1002, height = 555 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

