-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:74fc170efee5abc4434d86a490a1b120:1/1$
-- 

return {
	texture = 'llaxonDestroyerPack.png',
	frames = {
			{
				name = "llaxonDestroyer1.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.491211, v0 = 0.491211, u1 = 0.749512, v1 = 0.735352 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer10.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.750488, v0 = 0.246094, u1 = 0.994629, v1 = 0.504395 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer2.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.491211, v0 = 0.246094, u1 = 0.749512, v1 = 0.490234 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer3.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.246094, v0 = 0.505371, u1 = 0.490234, v1 = 0.763672 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer4.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.246094, v0 = 0.246094, u1 = 0.490234, v1 = 0.504395 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer5.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.505371, v0 = 0.000976562, u1 = 0.763672, v1 = 0.245117 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer6.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.246094, v0 = 0.000976562, u1 = 0.504395, v1 = 0.245117 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonDestroyer7.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.000976562, v0 = 0.519531, u1 = 0.245117, v1 = 0.777832 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer8.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.000976562, v0 = 0.260254, u1 = 0.245117, v1 = 0.518555 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyer9.png",
				spriteColorRect = { x = 0, y = 0, width = 500, height = 529 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.245117, v1 = 0.259277 },
				spriteSourceSize = { width = 500, height = 529 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyerIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.0893555, v0 = 0.778809, u1 = 0.23584, v1 = 0.925293 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonDestroyerTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 179, height = 400 },
				uvRect = { u0 = 0.000976562, v0 = 0.778809, u1 = 0.0883789, v1 = 0.974121 },
				spriteSourceSize = { width = 179, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

