-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:996085e294f2450792b005750b4872d2:1/1$
-- 

return {
	texture = 'llaxonFighterPack.png',
	frames = {
			{
				name = "llaxonFighter1.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.599609, v0 = 0.561523, u1 = 0.896484, v1 = 0.84082 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter10.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.599609, v0 = 0.28125, u1 = 0.896484, v1 = 0.560547 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter2.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.00195312, v0 = 0.841797, u1 = 0.560547, v1 = 0.990234 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "llaxonFighter3.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.300781, v0 = 0.561523, u1 = 0.597656, v1 = 0.84082 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter4.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.599609, v0 = 0.000976562, u1 = 0.896484, v1 = 0.280273 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter5.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.300781, v0 = 0.28125, u1 = 0.597656, v1 = 0.560547 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter6.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.00195312, v0 = 0.561523, u1 = 0.298828, v1 = 0.84082 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter7.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.300781, v0 = 0.000976562, u1 = 0.597656, v1 = 0.280273 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter8.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.00195312, v0 = 0.28125, u1 = 0.298828, v1 = 0.560547 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighter9.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 572 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.298828, v1 = 0.280273 },
				spriteSourceSize = { width = 304, height = 572 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "llaxonFighterIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.5625, v0 = 0.841797, u1 = 0.855469, v1 = 0.988281 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

