-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:4bb90091f1fc7752ec6697a1aa54708e:1/1$
-- 

return {
	texture = 'antHivePack.png',
	frames = {
			{
				name = "antHive1.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.492188, v0 = 0.488281, u1 = 0.980469, v1 = 0.730957 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive10.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.00195312, v0 = 0.488281, u1 = 0.490234, v1 = 0.730957 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive2.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.00195312, v0 = 0.488281, u1 = 0.490234, v1 = 0.730957 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive3.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.492188, v0 = 0.244629, u1 = 0.980469, v1 = 0.487305 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive4.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.00195312, v0 = 0.244629, u1 = 0.490234, v1 = 0.487305 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive5.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.492188, v0 = 0.000976562, u1 = 0.980469, v1 = 0.243652 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive6.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.490234, v1 = 0.243652 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive7.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.492188, v0 = 0.000976562, u1 = 0.980469, v1 = 0.243652 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive8.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.00195312, v0 = 0.244629, u1 = 0.490234, v1 = 0.487305 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHive9.png",
				spriteColorRect = { x = 0, y = 0, width = 497, height = 500 },
				uvRect = { u0 = 0.492188, v0 = 0.244629, u1 = 0.980469, v1 = 0.487305 },
				spriteSourceSize = { width = 497, height = 500 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "antHiveIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 300, height = 300 },
				uvRect = { u0 = 0.00195312, v0 = 0.731934, u1 = 0.294922, v1 = 0.878418 },
				spriteSourceSize = { width = 300, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "antHiveTurret.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 200 },
				uvRect = { u0 = 0.00195312, v0 = 0.879395, u1 = 0.197266, v1 = 0.977051 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

