-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:abd7fb47b9c3e762b3096d7b2e0fb689$
-- 

return {
	texture = 'particlesPack.png',
	frames = {
			{
				name = "greyDot.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 10 },
				uvRect = { u0 = 0.125, v0 = 0.125, u1 = 0.75, v1 = 0.75 },
				spriteSourceSize = { width = 10, height = 10 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

