-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0adb24dd0fa0de2d2854bc5636bc4729:096196c2205d76b7d7a9c538e1e802cc:2b58aad1b11c9524d24c71e01f5fbc26$
-- 

return {
	texture = 'outroPack.png',
	frames = {
			{
				name = "colonyDeserted.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.589844, u1 = 0.392578, v1 = 0.931641 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "noHumansLeft.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.393555, u1 = 0.685547, v1 = 0.588867 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whereEvilHumans1.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.197266, u1 = 0.685547, v1 = 0.392578 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whereEvilHumans2.png",
				spriteColorRect = { x = 0, y = 0, width = 700, height = 400 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.685547, v1 = 0.196289 },
				spriteSourceSize = { width = 700, height = 400 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

